### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ecomkings** [reteps/arbitrage-moments#1]
A:\Documents\arbitrage-moments-master>python3 start.py
Traceback (most recent call last):
  File "start.py", line 25, in <module>
    if market['percent_volume'] >= MINIMUM_PERCENT_VOL and market['is_updated'] and (trades_into in ACCEPTABLE_TRADING_PAIRS or ALL_PAIRS):
KeyError: 'is_updated'

not to sure what's causing this error

**Comment by reteps** [comment]
oh crap I modified that package myself. Can you modify your `pymarketcap`

**Comment by reteps** [comment]
fixed
