### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by edenpan** [reteps/arbitrage-moments#10]
Hi, i run the test cmd and get the following error:
Traceback (most recent call last):
  File "./start", line 33, in <module>
    markets = cmc.markets(coin["id"])
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./start", line 35, in <module>
    markets = cmc.markets(coin["symbol"])
TypeError: string indices must be integers
I try to use the pymarketcap's ticker(100) directly, it seems the data structure outer is just data?
Is there anything wrong?
Thanks

**Comment by reteps** [comment]
i'll look into it!

**Comment by reteps** [comment]
another pymarketcap update broke it, i'll fix it.
