### ISSUE TITLE
Can i use this to find a arbitrage only in binance?

### ISSUE THREAD

**Issue by K4mB** [reteps/arbitrage-moments#12]
Do a triangle arbitrage in binance?

iota/btc - iota/eth - eth/btc

or

iota/bnb -iota/eth - eth/btc

**Comment by reteps** [comment]
probably. Try with these settings:

`python3 ./start --exchanges Binance --pairs IOTA BTC ETH`

**Comment by K4mB** [comment]
Sorry for reply now but i didn't saw you answered, don't do trades right?

**Comment by reteps** [comment]
nope. you can overlay this with code from the "ccxt" library on github
