### ISSUE TITLE
Newbie question - how to get running on windows?

### ISSUE THREAD

**Issue by zeusfuze** [reteps/arbitrage-moments#3]
I downloaded python and your code but I'm confused about how to get it running from there. I tried navigating to the directory I have the folder in and typing start into a python command prompt, but that doesn't seem to work. I also tried using a regular command prompt, but that didn't seem to work either.

I'm sure there's some kind of build process that I'm missing here, and I was wondering if you could give me some step by step instructions to help me get this running. I know this is a script kiddie question but I'd really appreciate your help since I don't understand python very well.

Thanks in advance!

**Comment by reteps** [comment]
try running `python3 ./start`
