### ISSUE TITLE
Removing certain exchanges / currencies from the bot?

### ISSUE THREAD

**Issue by zeusfuze** [reteps/arbitrage-moments#4]
Is there a way to get rid of the korean won entries, for example? I want to see all U.S. supported exchanges, including ones I might not know about at the moment, but I don't want to see ones that I can't use, such as the Chinese and Korean ones.

**Comment by reteps** [comment]
please look at the README for information. https://github.com/reteps/arbitrage-chances/blob/master/README.md.
use the `--pairs` to change the acceptable pairs. Use `--exchanges` to change the acceptable exchanges.
