### ISSUE TITLE
Syntax @line 60

### ISSUE THREAD

**Issue by wolf128058** [reteps/arbitrage-moments#5]
https://github.com/reteps/arbitrage-chances/blob/521e60ab4bff556b7a50fd170aae962479071be1/start#L60

I had the idea to search for crypto arbitrages, but i have nearly no skills in python. Sorry.
I was not able to scan the CMC-API for different prices on different exchanges.
Searching for a solution i found this sweet little peace of stuff. Thank you for your work!

But my console output and the Python linter at pythonbuddy.com tell me something about a syntax error in line 60.

Is this really a problem or am i wrong?

**Comment by reteps** [comment]
what's the error? Maybe pylinter wants double quotes?

**Comment by reteps** [comment]
It appears you may be using python2, not python3. I'll add a quick fix from https://stackoverflow.com/questions/20073639/python-syntaxerror-invalid-syntax-end.

**Comment by reteps** [comment]
Try using `python3 ./start` to get it to work.
