### ISSUE TITLE
Seek out implied altcoin cross pairs, rather than explicit cross pairs

### ISSUE THREAD

**Issue by leewenjie** [reteps/arbitrage-moments#6]
I think there can be more profit potential in the implied cross pairs. I.e. derive ethbtc pair from ethkrw, btckrw on Korean exchanges, rather than just the mainstream ethbtc pair on bittrex.

**Comment by reteps** [comment]
so you're saying a 2 trade arbitrage? Like eth > krw > btc?

**Comment by leewenjie** [comment]
yup, this is right

**Comment by leewenjie** [comment]
best if we can identify the zero fees exchanges for this

**Comment by shivamgoyal1** [comment]
There is many opportunities through doing a triangle arb involving fiat currency exchange for countries such as Brazil, South Africa and Zimbabwe. 
We should also explore those.
