### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by jpfleury** [reteps/arbitrage-moments#7]
Hi,

Running the script with Python 3.6.3, I have an attribute error:

~~~~~
Traceback (most recent call last):
  File "./start", line 33, in <module>
    markets = cmc.markets(coin["id"])
  File "/home/u/arbitrage-chances/lib/python3.6/site-packages/pymarketcap/core.py", line 296, in markets
    marks = html.find(id="markets-table").find("tbody").find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find'
~~~~~

I attach the complete output, including the command line used: [output-arbitrage-chances.txt](https://github.com/reteps/arbitrage-chances/files/1785492/output-arbitrage-chances.txt)

**Comment by reteps** [comment]
Seems like an error with the coin itself. Ill look into it.

**Comment by reteps** [comment]
that coin has no markets, but you shouldn't be getting so low in the rankings.

**Comment by reteps** [comment]
i'm gonna close this idk went wrong
