### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Addstorm** [reteps/arbitrage-moments#8]
Hi,

Running the script with Python 3.6.4 on Windows 10, I have a type error:

`Traceback (most recent call last):
  File "start.py", line 45, in <module>
    trades_into = market["pair"].replace(coin["symbol"],"").replace("-","")
TypeError: string indices must be integers`

I attach the complete output, including the command line used: [output-arbitrage-chances.txt](https://gist.github.com/Addstorm/75e13a2d6458315ffbf588d25ca660d9)

**Comment by reteps** [comment]
i'll work on it. keep you updated.

**Comment by reteps** [comment]
fixed in commit.
